---
title: "Interactive Exploration: What is a Derivative?"
format:
  html:
    toc: true
    code-fold: false
execute:
  echo: false
---

## Conceptual Definition of a Derivative
A derivative tells us how the slope of a function changes at any given point.  In most cases, we cannot precisely measure this.  Therefore, we measure it by seeing how the function changes when we move slightly from the point.

## Mathematical Definition of a Derivative
Consider a function f(x).  Now, we want to find the derivative at a point x = a.  We can compute f(a).  This tells us the value of  the function at x = a but not its slope.  To obtain the slope at that point, we take take another point close by (a + h) and compute the following:


$$
f'(a)
=
\left.\frac{df}{dx}\right|_{x=a}
=
\lim_{h \to 0}
\frac{f(a+h)-f(a)}{h}
$$

In other words we want to calculate the instantaneous change of f(x) for a small change in x at any given point where x = a.

## Why do we Study Derivatives?

Derivatives help us understand many things such as changes in temperature and how it impacts our body (when you get a fever, your body temperature has instantaneously changed to a higher value and as a result you feel sick).  It also helps us understand how your speedometer in your car tell us the instantaneous velocity (say 30 mph) and how you can use your steering and brakes to change to another value to either move quickly or slowly.  A flood gage tells you how the river height changes over time in response to rainfall and heat.  Look around and you will see how calculus helps us think about changes of one variable and how it impacts something that depends on it.

## Exploratory Example

In this example you will understand how the derivative changes with time in a rollercoaster.  When the derivative (or the instantaneous slope) is negative you will feel the push towards the ground due to gravity, while the slope is positive you will feel the pull away from the ground.  Roller coasters suddenly change the instaneous slopes,(both direction and magnitude), or derivatives to create thrill!!

---

**Instructions**

- Click the link.
- Wait for Colab to open.
- Choose **Runtime → Run all**.
-  Move the sliders and answer the questions below.

---

::: {.callout-tip}
## 🚀 Interactive Exploration

Use the interactive notebook to explore how the derivative changes over time in a roller coaster.

[Open in Google Colab](https://colab.research.google.com/github/vuddameri/Calculus-I/blob/main/notebooks/rollercoaster.ipynb)

:::

## Summary

In this activity you discovered that

- A derivative measures **change**.
- The derivative depends on **where** you are on the graph.
- The tangent line gives the **instantaneous rate of change**.
- A derivative has physical meaning—in this example, it represents velocity.

---

